import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { jsPDF } from 'jspdf';


@Component({
  selector: 'app-billing',
  standalone: true,
  templateUrl: './billing.component.html',
  styleUrls: ['./billing.component.scss'],
	imports: [
		CommonModule,
		FormsModule
	],
	providers: [],
})
export class BillingComponent {
  parents: any[] = [
    { name: 'John Doe', subscription: 'Monthly', amount: 100, status: 'Due' },
    { name: 'Jane Smith', subscription: 'Quarterly', amount: 300, status: 'Paid' },
    { name: 'Alice Johnson', subscription: 'Yearly', amount: 1200, status: 'Due' },
  ];

  showPaymentModal: boolean = false;
  selectedParent: any = null;
  paymentDetails: any = { mode: 'cash', amount: 0 };

  generateInvoice(parent: any): void {
    this.selectedParent = parent;
    this.showPaymentModal = true;
  }

  generateReport(parent: any): void {
    const doc = new jsPDF();

    // Add title
    doc.setFontSize(18);
    doc.text('Payment Report', 105, 20, { align: 'center' });

    // Add parent details
    doc.setFontSize(12);
    doc.text(`Parent Name: ${parent.name}`, 20, 40);
    doc.text(`Subscription: ${parent.subscription}`, 20, 50);
    doc.text(`Amount: $${parent.amount}`, 20, 60);
    doc.text(`Status: ${parent.status}`, 20, 70);

    // Add footer
    doc.setFontSize(10);
    doc.text('Generated by Billing System', 105, 290, { align: 'center' });

    // Save the PDF
    doc.save(`${parent.name}_Payment_Report.pdf`);
  }

  recordPayment(): void {
    if (this.selectedParent) {
      this.selectedParent.status = 'Paid';
      this.selectedParent.amount = 0; // Clear the amount after payment
      this.closePaymentModal();
    }
  }

  closePaymentModal(): void {
    this.showPaymentModal = false;
    this.selectedParent = null;
    this.paymentDetails = { mode: 'cash', amount: 0 };
  }
}
