// Theatre Mock Data with Bhutanese Names and Locations

import {
	Theatre,
	Hall,
	TheatreStatus,
	HallStatus,
	HallType,
	SeatCategory,
	SoundSystem,
	ProjectionType,
	TheatreFacility,
	HallFeature,
	AccessibilityFeature,
	OperatingHours,
	SeatLayout,
	HallPricing,
} from './theatre.dto';

// Bhutanese Theatre Names and Locations
export const BHUTANESE_THEATRE_MOCK_DATA: Theatre[] = [
	{
		id: 'theatre-001',
		name: 'Druk Deothjung Cinema',
		location: 'Norzin Lam',
		address: 'Norzin Lam, Near Clock Tower Square',
		city: 'Thimphu',
		district: 'Thimphu',
		phone: '+975-2-322-456',
		email: 'info@drukdeothjung.bt',
		description:
			'Premier entertainment destination in the heart of Thimphu, offering state-of-the-art cinema experience with traditional Bhutanese hospitality.',
		image: '/assets/images/theatres/druk-deothjung.jpg',
		status: TheatreStatus.ACTIVE,
		facilities: [
			TheatreFacility.PARKING,
			TheatreFacility.FOOD_COURT,
			TheatreFacility.COFFEE_SHOP,
			TheatreFacility.WIFI,
			TheatreFacility.ATM,
			TheatreFacility.CHARGING_STATIONS,
			TheatreFacility.ELEVATORS,
		],
		operatingHours: {
			monday: {
				isOpen: true,
				openTime: '10:00',
				closeTime: '23:00',
				breaks: [],
			},
			tuesday: {
				isOpen: true,
				openTime: '10:00',
				closeTime: '23:00',
				breaks: [],
			},
			wednesday: {
				isOpen: true,
				openTime: '10:00',
				closeTime: '23:00',
				breaks: [],
			},
			thursday: {
				isOpen: true,
				openTime: '10:00',
				closeTime: '23:00',
				breaks: [],
			},
			friday: {
				isOpen: true,
				openTime: '10:00',
				closeTime: '23:30',
				breaks: [],
			},
			saturday: {
				isOpen: true,
				openTime: '09:00',
				closeTime: '23:30',
				breaks: [],
			},
			sunday: {
				isOpen: true,
				openTime: '09:00',
				closeTime: '23:00',
				breaks: [],
			},
		},
		totalHalls: 4,
		totalSeats: 650,
		createdAt: new Date('2020-01-15'),
		updatedAt: new Date('2024-11-01'),
		halls: [],
	},
	{
		id: 'theatre-002',
		name: 'Penden Multiplex',
		location: 'Babesa',
		address: 'Babesa, Near Centenary Farmers Market',
		city: 'Thimphu',
		district: 'Thimphu',
		phone: '+975-2-351-789',
		email: 'contact@pendenmultiplex.bt',
		description:
			'Modern multiplex cinema featuring the latest technology and comfortable seating, located in the bustling Babesa area.',
		image: '/assets/images/theatres/penden-multiplex.jpg',
		status: TheatreStatus.ACTIVE,
		facilities: [
			TheatreFacility.PARKING,
			TheatreFacility.RESTAURANT,
			TheatreFacility.GIFT_SHOP,
			TheatreFacility.KIDS_PLAY_AREA,
			TheatreFacility.GAMING_ZONE,
			TheatreFacility.WIFI,
			TheatreFacility.CHARGING_STATIONS,
		],
		operatingHours: {
			monday: {
				isOpen: true,
				openTime: '11:00',
				closeTime: '22:30',
				breaks: [],
			},
			tuesday: {
				isOpen: true,
				openTime: '11:00',
				closeTime: '22:30',
				breaks: [],
			},
			wednesday: {
				isOpen: true,
				openTime: '11:00',
				closeTime: '22:30',
				breaks: [],
			},
			thursday: {
				isOpen: true,
				openTime: '11:00',
				closeTime: '22:30',
				breaks: [],
			},
			friday: {
				isOpen: true,
				openTime: '11:00',
				closeTime: '23:00',
				breaks: [],
			},
			saturday: {
				isOpen: true,
				openTime: '10:00',
				closeTime: '23:00',
				breaks: [],
			},
			sunday: {
				isOpen: true,
				openTime: '10:00',
				closeTime: '22:30',
				breaks: [],
			},
		},
		totalHalls: 6,
		totalSeats: 920,
		createdAt: new Date('2021-03-20'),
		updatedAt: new Date('2024-10-15'),
		halls: [],
	},
	{
		id: 'theatre-003',
		name: 'Tashichho Dzong Cinema',
		location: 'Tashichho Dzong Area',
		address: 'Near Tashichho Dzong, Government Quarter',
		city: 'Thimphu',
		district: 'Thimphu',
		phone: '+975-2-325-123',
		email: 'admin@tashichhodzong.bt',
		description:
			'Heritage cinema hall offering premium movie experience with views of the majestic Tashichho Dzong fortress.',
		image: '/assets/images/theatres/tashichho-cinema.jpg',
		status: TheatreStatus.ACTIVE,
		facilities: [
			TheatreFacility.PARKING,
			TheatreFacility.COFFEE_SHOP,
			TheatreFacility.WIFI,
			TheatreFacility.CHARGING_STATIONS,
		],
		operatingHours: {
			monday: {
				isOpen: true,
				openTime: '12:00',
				closeTime: '22:00',
				breaks: [],
			},
			tuesday: {
				isOpen: true,
				openTime: '12:00',
				closeTime: '22:00',
				breaks: [],
			},
			wednesday: {
				isOpen: true,
				openTime: '12:00',
				closeTime: '22:00',
				breaks: [],
			},
			thursday: {
				isOpen: true,
				openTime: '12:00',
				closeTime: '22:00',
				breaks: [],
			},
			friday: {
				isOpen: true,
				openTime: '12:00',
				closeTime: '22:30',
				breaks: [],
			},
			saturday: {
				isOpen: true,
				openTime: '11:00',
				closeTime: '22:30',
				breaks: [],
			},
			sunday: {
				isOpen: true,
				openTime: '11:00',
				closeTime: '22:00',
				breaks: [],
			},
		},
		totalHalls: 3,
		totalSeats: 450,
		createdAt: new Date('2019-08-10'),
		updatedAt: new Date('2024-09-20'),
		halls: [],
	},
	{
		id: 'theatre-004',
		name: 'Phuntsholing Gateway Cinema',
		location: 'Phuntsholing Town',
		address: 'Main Bazaar, Phuntsholing',
		city: 'Phuntsholing',
		district: 'Chukha',
		phone: '+975-5-252-567',
		email: 'info@phuntsholinggateway.bt',
		description:
			'Border town cinema serving both Bhutanese and Indian audiences with diverse movie selections and modern amenities.',
		image: '/assets/images/theatres/phuntsholing-gateway.jpg',
		status: TheatreStatus.ACTIVE,
		facilities: [
			TheatreFacility.PARKING,
			TheatreFacility.FOOD_COURT,
			TheatreFacility.RESTAURANT,
			TheatreFacility.ATM,
			TheatreFacility.WIFI,
			TheatreFacility.CHARGING_STATIONS,
		],
		operatingHours: {
			monday: {
				isOpen: true,
				openTime: '10:00',
				closeTime: '23:00',
				breaks: [],
			},
			tuesday: {
				isOpen: true,
				openTime: '10:00',
				closeTime: '23:00',
				breaks: [],
			},
			wednesday: {
				isOpen: true,
				openTime: '10:00',
				closeTime: '23:00',
				breaks: [],
			},
			thursday: {
				isOpen: true,
				openTime: '10:00',
				closeTime: '23:00',
				breaks: [],
			},
			friday: {
				isOpen: true,
				openTime: '10:00',
				closeTime: '23:30',
				breaks: [],
			},
			saturday: {
				isOpen: true,
				openTime: '09:30',
				closeTime: '23:30',
				breaks: [],
			},
			sunday: {
				isOpen: true,
				openTime: '09:30',
				closeTime: '23:00',
				breaks: [],
			},
		},
		totalHalls: 5,
		totalSeats: 780,
		createdAt: new Date('2020-11-05'),
		updatedAt: new Date('2024-10-30'),
		halls: [],
	},
	{
		id: 'theatre-005',
		name: 'Punakha Valley Cinema',
		location: 'Punakha Dzong Chhu',
		address: 'Near Punakha Dzong, Mo Chhu Bridge',
		city: 'Punakha',
		district: 'Punakha',
		phone: '+975-2-584-234',
		email: 'contact@punakhavalley.bt',
		description:
			'Scenic cinema hall located in the beautiful Punakha valley, offering a unique movie experience amidst natural beauty.',
		image: '/assets/images/theatres/punakha-valley.jpg',
		status: TheatreStatus.MAINTENANCE,
		facilities: [
			TheatreFacility.PARKING,
			TheatreFacility.COFFEE_SHOP,
			TheatreFacility.WIFI,
			TheatreFacility.CHARGING_STATIONS,
		],
		operatingHours: {
			monday: {
				isOpen: false,
				openTime: '12:00',
				closeTime: '21:00',
				breaks: [],
			},
			tuesday: {
				isOpen: false,
				openTime: '12:00',
				closeTime: '21:00',
				breaks: [],
			},
			wednesday: {
				isOpen: false,
				openTime: '12:00',
				closeTime: '21:00',
				breaks: [],
			},
			thursday: {
				isOpen: false,
				openTime: '12:00',
				closeTime: '21:00',
				breaks: [],
			},
			friday: {
				isOpen: false,
				openTime: '12:00',
				closeTime: '21:30',
				breaks: [],
			},
			saturday: {
				isOpen: false,
				openTime: '11:00',
				closeTime: '21:30',
				breaks: [],
			},
			sunday: {
				isOpen: false,
				openTime: '11:00',
				closeTime: '21:00',
				breaks: [],
			},
		},
		totalHalls: 2,
		totalSeats: 280,
		createdAt: new Date('2022-06-18'),
		updatedAt: new Date('2024-11-15'),
		halls: [],
	},
	{
		id: 'theatre-006',
		name: 'Paro International Cinema',
		location: 'Paro Airport Road',
		address: 'Airport Road, Near Paro International Airport',
		city: 'Paro',
		district: 'Paro',
		phone: '+975-8-271-890',
		email: 'info@parointernational.bt',
		description:
			'International standard cinema catering to tourists and locals alike, featuring both Bhutanese and international films.',
		image: '/assets/images/theatres/paro-international.jpg',
		status: TheatreStatus.ACTIVE,
		facilities: [
			TheatreFacility.PARKING,
			TheatreFacility.RESTAURANT,
			TheatreFacility.GIFT_SHOP,
			TheatreFacility.WIFI,
			TheatreFacility.ATM,
			TheatreFacility.CHARGING_STATIONS,
			TheatreFacility.ELEVATORS,
		],
		operatingHours: {
			monday: {
				isOpen: true,
				openTime: '11:00',
				closeTime: '22:00',
				breaks: [],
			},
			tuesday: {
				isOpen: true,
				openTime: '11:00',
				closeTime: '22:00',
				breaks: [],
			},
			wednesday: {
				isOpen: true,
				openTime: '11:00',
				closeTime: '22:00',
				breaks: [],
			},
			thursday: {
				isOpen: true,
				openTime: '11:00',
				closeTime: '22:00',
				breaks: [],
			},
			friday: {
				isOpen: true,
				openTime: '11:00',
				closeTime: '22:30',
				breaks: [],
			},
			saturday: {
				isOpen: true,
				openTime: '10:30',
				closeTime: '22:30',
				breaks: [],
			},
			sunday: {
				isOpen: true,
				openTime: '10:30',
				closeTime: '22:00',
				breaks: [],
			},
		},
		totalHalls: 4,
		totalSeats: 560,
		createdAt: new Date('2021-09-12'),
		updatedAt: new Date('2024-10-08'),
		halls: [],
	},
];

// Bhutanese Hall Names for each Theatre
export const BHUTANESE_HALLS_MOCK_DATA: Hall[] = [
	// Druk Deothjung Cinema Halls
	{
		id: 'hall-001',
		theatreId: 'theatre-001',
		name: 'Tenzin Premium Hall',
		type: HallType.PREMIUM,
		capacity: 180,
		status: HallStatus.ACTIVE,
		seatLayout: {
			rows: 12,
			seatsPerRow: 15,
			seatTypes: [
				{
					type: SeatCategory.REGULAR,
					count: 120,
					price: 150,
					color: '#94a3b8',
					rows: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
				},
				{
					type: SeatCategory.PREMIUM,
					count: 60,
					price: 250,
					color: '#f59e0b',
					rows: ['I', 'J', 'K', 'L'],
				},
			],
			aisles: [{ afterRow: 6, width: 1.5 }],
		},
		features: [
			HallFeature.RECLINER_SEATS,
			HallFeature.LEATHER_SEATS,
			HallFeature.BEVERAGE_SERVICE,
		],
		soundSystem: SoundSystem.DOLBY_ATMOS,
		projectionType: [
			ProjectionType.DIGITAL_2D,
			ProjectionType.DIGITAL_3D,
			ProjectionType.DOLBY_VISION,
		],
		airConditioning: true,
		accessibility: [
			AccessibilityFeature.WHEELCHAIR_ACCESS,
			AccessibilityFeature.HEARING_ASSISTANCE,
		],
		pricing: {
			basePrice: 150,
			premiumPrice: 250,
			vipPrice: 0,
			weekendSurcharge: 50,
			holidaySurcharge: 75,
		},
		createdAt: new Date('2020-01-15'),
		updatedAt: new Date('2024-11-01'),
	},
	{
		id: 'hall-002',
		theatreId: 'theatre-001',
		name: 'Pema IMAX Hall',
		type: HallType.IMAX,
		capacity: 220,
		status: HallStatus.ACTIVE,
		seatLayout: {
			rows: 15,
			seatsPerRow: 16,
			seatTypes: [
				{
					type: SeatCategory.REGULAR,
					count: 140,
					price: 200,
					color: '#94a3b8',
					rows: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
				},
				{
					type: SeatCategory.PREMIUM,
					count: 80,
					price: 350,
					color: '#f59e0b',
					rows: ['J', 'K', 'L', 'M', 'N', 'O'],
				},
			],
			aisles: [{ afterRow: 8, width: 2.0 }],
		},
		features: [
			HallFeature.RECLINER_SEATS,
			HallFeature.HEATED_SEATS,
			HallFeature.DINING_SERVICE,
		],
		soundSystem: SoundSystem.IMAX_ENHANCED,
		projectionType: [
			ProjectionType.IMAX,
			ProjectionType.LASER,
			ProjectionType.HDR,
		],
		airConditioning: true,
		accessibility: [
			AccessibilityFeature.WHEELCHAIR_ACCESS,
			AccessibilityFeature.HEARING_ASSISTANCE,
			AccessibilityFeature.WIDE_DOORS,
		],
		pricing: {
			basePrice: 200,
			premiumPrice: 350,
			vipPrice: 0,
			weekendSurcharge: 75,
			holidaySurcharge: 100,
		},
		createdAt: new Date('2020-01-15'),
		updatedAt: new Date('2024-11-01'),
	},
	{
		id: 'hall-003',
		theatreId: 'theatre-001',
		name: 'Karma Standard Hall',
		type: HallType.STANDARD,
		capacity: 150,
		status: HallStatus.ACTIVE,
		seatLayout: {
			rows: 10,
			seatsPerRow: 15,
			seatTypes: [
				{
					type: SeatCategory.REGULAR,
					count: 150,
					price: 120,
					color: '#94a3b8',
					rows: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
				},
			],
			aisles: [{ afterRow: 5, width: 1.0 }],
		},
		features: [HallFeature.LEATHER_SEATS],
		soundSystem: SoundSystem.SURROUND_7_1,
		projectionType: [ProjectionType.DIGITAL_2D, ProjectionType.DIGITAL_3D],
		airConditioning: true,
		accessibility: [AccessibilityFeature.WHEELCHAIR_ACCESS],
		pricing: {
			basePrice: 120,
			premiumPrice: 0,
			vipPrice: 0,
			weekendSurcharge: 30,
			holidaySurcharge: 50,
		},
		createdAt: new Date('2020-01-15'),
		updatedAt: new Date('2024-11-01'),
	},
	{
		id: 'hall-004',
		theatreId: 'theatre-001',
		name: 'Dolma VIP Lounge',
		type: HallType.VIP,
		capacity: 100,
		status: HallStatus.ACTIVE,
		seatLayout: {
			rows: 8,
			seatsPerRow: 12,
			seatTypes: [
				{
					type: SeatCategory.VIP,
					count: 80,
					price: 500,
					color: '#dc2626',
					rows: ['A', 'B', 'C', 'D', 'E', 'F'],
				},
				{
					type: SeatCategory.COUPLE,
					count: 20,
					price: 800,
					color: '#be185d',
					rows: ['G', 'H'],
				},
			],
			aisles: [{ afterRow: 4, width: 2.5 }],
		},
		features: [
			HallFeature.MASSAGE_SEATS,
			HallFeature.DINING_SERVICE,
			HallFeature.PRIVATE_ENTRANCE,
			HallFeature.BEVERAGE_SERVICE,
		],
		soundSystem: SoundSystem.DOLBY_ATMOS,
		projectionType: [
			ProjectionType.DIGITAL_2D,
			ProjectionType.DIGITAL_3D,
			ProjectionType.DOLBY_VISION,
		],
		airConditioning: true,
		accessibility: [
			AccessibilityFeature.WHEELCHAIR_ACCESS,
			AccessibilityFeature.HEARING_ASSISTANCE,
			AccessibilityFeature.ACCESSIBLE_RESTROOMS,
		],
		pricing: {
			basePrice: 0,
			premiumPrice: 0,
			vipPrice: 500,
			weekendSurcharge: 100,
			holidaySurcharge: 150,
		},
		createdAt: new Date('2020-01-15'),
		updatedAt: new Date('2024-11-01'),
	},

	// Penden Multiplex Halls
	{
		id: 'hall-005',
		theatreId: 'theatre-002',
		name: 'Sonam Grand Hall',
		type: HallType.PREMIUM,
		capacity: 200,
		status: HallStatus.ACTIVE,
		seatLayout: {
			rows: 13,
			seatsPerRow: 16,
			seatTypes: [
				{
					type: SeatCategory.REGULAR,
					count: 128,
					price: 160,
					color: '#94a3b8',
					rows: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
				},
				{
					type: SeatCategory.PREMIUM,
					count: 72,
					price: 280,
					color: '#f59e0b',
					rows: ['I', 'J', 'K', 'L', 'M'],
				},
			],
			aisles: [{ afterRow: 7, width: 1.8 }],
		},
		features: [
			HallFeature.RECLINER_SEATS,
			HallFeature.LEATHER_SEATS,
			HallFeature.BEVERAGE_SERVICE,
		],
		soundSystem: SoundSystem.DOLBY_ATMOS,
		projectionType: [
			ProjectionType.DIGITAL_2D,
			ProjectionType.DIGITAL_3D,
			ProjectionType.DOLBY_VISION,
		],
		airConditioning: true,
		accessibility: [
			AccessibilityFeature.WHEELCHAIR_ACCESS,
			AccessibilityFeature.HEARING_ASSISTANCE,
		],
		pricing: {
			basePrice: 160,
			premiumPrice: 280,
			vipPrice: 0,
			weekendSurcharge: 60,
			holidaySurcharge: 80,
		},
		createdAt: new Date('2021-03-20'),
		updatedAt: new Date('2024-10-15'),
	},
	{
		id: 'hall-006',
		theatreId: 'theatre-002',
		name: 'Dechen Standard Hall',
		type: HallType.STANDARD,
		capacity: 140,
		status: HallStatus.ACTIVE,
		seatLayout: {
			rows: 10,
			seatsPerRow: 14,
			seatTypes: [
				{
					type: SeatCategory.REGULAR,
					count: 140,
					price: 130,
					color: '#94a3b8',
					rows: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
				},
			],
			aisles: [{ afterRow: 5, width: 1.2 }],
		},
		features: [HallFeature.LEATHER_SEATS],
		soundSystem: SoundSystem.SURROUND_7_1,
		projectionType: [ProjectionType.DIGITAL_2D, ProjectionType.DIGITAL_3D],
		airConditioning: true,
		accessibility: [AccessibilityFeature.WHEELCHAIR_ACCESS],
		pricing: {
			basePrice: 130,
			premiumPrice: 0,
			vipPrice: 0,
			weekendSurcharge: 40,
			holidaySurcharge: 60,
		},
		createdAt: new Date('2021-03-20'),
		updatedAt: new Date('2024-10-15'),
	},
	{
		id: 'hall-007',
		theatreId: 'theatre-002',
		name: 'Lhamo Premium Hall',
		type: HallType.PREMIUM,
		capacity: 180,
		status: HallStatus.CLEANING,
		seatLayout: {
			rows: 12,
			seatsPerRow: 15,
			seatTypes: [
				{
					type: SeatCategory.REGULAR,
					count: 120,
					price: 170,
					color: '#94a3b8',
					rows: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
				},
				{
					type: SeatCategory.PREMIUM,
					count: 60,
					price: 290,
					color: '#f59e0b',
					rows: ['I', 'J', 'K', 'L'],
				},
			],
			aisles: [{ afterRow: 6, width: 1.5 }],
		},
		features: [HallFeature.RECLINER_SEATS, HallFeature.HEATED_SEATS],
		soundSystem: SoundSystem.DOLBY_ATMOS,
		projectionType: [ProjectionType.DIGITAL_2D, ProjectionType.DIGITAL_3D],
		airConditioning: true,
		accessibility: [
			AccessibilityFeature.WHEELCHAIR_ACCESS,
			AccessibilityFeature.HEARING_ASSISTANCE,
		],
		pricing: {
			basePrice: 170,
			premiumPrice: 290,
			vipPrice: 0,
			weekendSurcharge: 65,
			holidaySurcharge: 85,
		},
		createdAt: new Date('2021-03-20'),
		updatedAt: new Date('2024-10-15'),
	},

	// Additional halls for other theatres...
	{
		id: 'hall-008',
		theatreId: 'theatre-003',
		name: 'Wangchuk Heritage Hall',
		type: HallType.PREMIUM,
		capacity: 180,
		status: HallStatus.ACTIVE,
		seatLayout: {
			rows: 12,
			seatsPerRow: 15,
			seatTypes: [
				{
					type: SeatCategory.REGULAR,
					count: 120,
					price: 140,
					color: '#94a3b8',
					rows: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
				},
				{
					type: SeatCategory.PREMIUM,
					count: 60,
					price: 240,
					color: '#f59e0b',
					rows: ['I', 'J', 'K', 'L'],
				},
			],
			aisles: [{ afterRow: 6, width: 1.5 }],
		},
		features: [HallFeature.LEATHER_SEATS, HallFeature.BEVERAGE_SERVICE],
		soundSystem: SoundSystem.SURROUND_7_1,
		projectionType: [ProjectionType.DIGITAL_2D, ProjectionType.DIGITAL_3D],
		airConditioning: true,
		accessibility: [AccessibilityFeature.WHEELCHAIR_ACCESS],
		pricing: {
			basePrice: 140,
			premiumPrice: 240,
			vipPrice: 0,
			weekendSurcharge: 45,
			holidaySurcharge: 70,
		},
		createdAt: new Date('2019-08-10'),
		updatedAt: new Date('2024-09-20'),
	},
];

// Utility functions for mock data
export const getBhutaneseTheatres = (): Theatre[] => {
	return BHUTANESE_THEATRE_MOCK_DATA.map((theatre) => ({
		...theatre,
		halls: BHUTANESE_HALLS_MOCK_DATA.filter(
			(hall) => hall.theatreId === theatre.id
		),
	}));
};

export const getBhutaneseHallsByTheatre = (theatreId: string): Hall[] => {
	return BHUTANESE_HALLS_MOCK_DATA.filter(
		(hall) => hall.theatreId === theatreId
	);
};

export const getTheatreStats = () => {
	const theatres = getBhutaneseTheatres();
	return {
		totalTheatres: theatres.length,
		activeTheatres: theatres.filter((t) => t.status === TheatreStatus.ACTIVE)
			.length,
		totalHalls: theatres.reduce((sum, t) => sum + t.totalHalls, 0),
		totalSeats: theatres.reduce((sum, t) => sum + t.totalSeats, 0),
		averageOccupancy: 72.5,
		topPerformingTheatre: theatres[1], // Penden Multiplex
		revenueByTheatre: theatres.map((t) => ({
			theatreId: t.id,
			name: t.name,
			revenue: Math.floor(Math.random() * 500000) + 100000,
		})),
	};
};

// Bhutanese district and city data
export const BHUTANESE_LOCATIONS = {
	districts: [
		'Thimphu',
		'Paro',
		'Punakha',
		'Wangdue Phodrang',
		'Bumthang',
		'Trongsa',
		'Mongar',
		'Lhuentse',
		'Trashigang',
		'Samdrup Jongkhar',
		'Samtse',
		'Chukha',
		'Haa',
		'Dagana',
		'Sarpang',
		'Tsirang',
		'Zhemgang',
		'Pemagatshel',
		'Trashiyangtse',
		'Gasa',
	],
	cities: {
		Thimphu: ['Thimphu', 'Babesa', 'Dechencholing', 'Taba', 'Simtokha'],
		Paro: ['Paro', 'Drugyel', 'Bondey', 'Shaba'],
		Punakha: ['Punakha', 'Wangdi', 'Khuruthang', 'Lobesa'],
		Chukha: ['Phuntsholing', 'Gedu', 'Phuentsholing', 'Chhukha'],
		'Wangdue Phodrang': ['Bajo', 'Wangdue', 'Thedtsho'],
		Bumthang: ['Jakar', 'Chamkhar', 'Ura', 'Tang'],
	},
};
