import {
	IMovie,
	MovieGenre,
	MovieRating,
	MovieStatus,
	MovieLanguage,
	MovieCast,
	MovieCrew,
	MovieRatings,
	MovieTrailer,
	MovieSchedule,
	MovieReview,
} from './movie.dto';

// Mock cast data
const mockCast: MovieCast[] = [
	{
		id: '1',
		name: 'Christian Bale',
		role: 'Actor',
		character: 'Bruce Wayne / Batman',
		profileImage: '/assets/avatars/christian-bale.jpg',
		isMainCast: true,
	},
	{
		id: '2',
		name: 'Heath Ledger',
		role: 'Actor',
		character: 'The Joker',
		profileImage: '/assets/avatars/heath-ledger.jpg',
		isMainCast: true,
	},
	{
		id: '3',
		name: 'Aaron Eckhart',
		role: 'Actor',
		character: 'Harvey Dent / Two-Face',
		profileImage: '/assets/avatars/aaron-eckhart.jpg',
		isMainCast: true,
	},
	{
		id: '4',
		name: 'Michael Caine',
		role: 'Actor',
		character: 'Alfred Pennyworth',
		profileImage: '/assets/avatars/michael-caine.jpg',
		isMainCast: false,
	},
	{
		id: '5',
		name: 'Maggie Gyllenhaal',
		role: 'Actor',
		character: 'Rachel Dawes',
		profileImage: '/assets/avatars/maggie-gyllenhaal.jpg',
		isMainCast: false,
	},
];

// Mock crew data
const mockCrew: MovieCrew[] = [
	{
		id: '1',
		name: 'Christopher Nolan',
		role: 'Director',
		profileImage: '/assets/avatars/christopher-nolan.jpg',
	},
	{
		id: '2',
		name: 'Jonathan Nolan',
		role: 'Writer',
		profileImage: '/assets/avatars/jonathan-nolan.jpg',
	},
	{
		id: '3',
		name: 'David S. Goyer',
		role: 'Writer',
		profileImage: '/assets/avatars/david-goyer.jpg',
	},
	{
		id: '4',
		name: 'Wally Pfister',
		role: 'Cinematographer',
		profileImage: '/assets/avatars/wally-pfister.jpg',
	},
	{
		id: '5',
		name: 'Hans Zimmer',
		role: 'Composer',
		profileImage: '/assets/avatars/hans-zimmer.jpg',
	},
];

// Mock ratings
const mockRatings: MovieRatings = {
	imdb: 9.0,
	rottenTomatoes: 94,
	metacritic: 84,
	audienceScore: 94,
	totalReviews: 2847639,
	averageRating: 4.5,
};

// Mock trailers
const mockTrailers: MovieTrailer[] = [
	{
		id: '1',
		title: 'The Dark Knight - Official Trailer',
		url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
		thumbnailUrl: '/assets/movies/dark-knight-trailer-thumb.jpg',
		duration: 150,
		isOfficial: true,
	},
	{
		id: '2',
		title: 'The Dark Knight - Teaser Trailer',
		url: 'https://www.youtube.com/watch?v=UWw0ov-cAUg',
		thumbnailUrl: '/assets/movies/dark-knight-teaser-thumb.jpg',
		duration: 90,
		isOfficial: true,
	},
];

// Mock schedules
const mockSchedules: MovieSchedule[] = [
	{
		id: '1',
		theaterId: 'theater-1',
		theaterName: 'CineMax Theater',
		screenId: 'screen-1',
		screenName: 'Screen 1',
		showTime: new Date('2025-06-07T14:00:00'),
		endTime: new Date('2025-06-07T16:32:00'),
		availableSeats: 85,
		totalSeats: 120,
		basePrice: 250,
		premiumPrice: 350,
		isActive: true,
	},
	{
		id: '2',
		theaterId: 'theater-1',
		theaterName: 'CineMax Theater',
		screenId: 'screen-2',
		screenName: 'Screen 2 IMAX',
		showTime: new Date('2025-06-07T18:30:00'),
		endTime: new Date('2025-06-07T21:02:00'),
		availableSeats: 45,
		totalSeats: 80,
		basePrice: 450,
		premiumPrice: 650,
		isActive: true,
	},
	{
		id: '3',
		theaterId: 'theater-2',
		theaterName: 'MovieMax Cinema',
		screenId: 'screen-3',
		screenName: 'Screen 1',
		showTime: new Date('2025-06-07T21:15:00'),
		endTime: new Date('2025-06-07T23:47:00'),
		availableSeats: 92,
		totalSeats: 150,
		basePrice: 220,
		premiumPrice: 320,
		isActive: true,
	},
];

// Mock reviews
const mockReviews: MovieReview[] = [
	{
		id: '1',
		userId: 'user-1',
		userName: 'John Doe',
		userAvatar: '/assets/avatars/user-1.jpg',
		rating: 5,
		comment:
			"Absolutely phenomenal movie! Heath Ledger's performance as the Joker is legendary. A masterpiece of cinema.",
		createdAt: new Date('2025-05-15T10:30:00'),
		isVerifiedBooking: true,
		helpfulCount: 45,
		reportCount: 0,
	},
	{
		id: '2',
		userId: 'user-2',
		userName: 'Jane Smith',
		userAvatar: '/assets/avatars/user-2.jpg',
		rating: 5,
		comment:
			'Christopher Nolan at his finest. The story, the action, the characters - everything is perfect. Must watch!',
		createdAt: new Date('2025-05-20T15:45:00'),
		isVerifiedBooking: true,
		helpfulCount: 32,
		reportCount: 0,
	},
	{
		id: '3',
		userId: 'user-3',
		userName: 'Mike Johnson',
		userAvatar: '/assets/avatars/user-3.jpg',
		rating: 4,
		comment:
			'Great movie with excellent cinematography and soundtrack. Heath Ledger steals every scene.',
		createdAt: new Date('2025-06-01T20:15:00'),
		isVerifiedBooking: false,
		helpfulCount: 18,
		reportCount: 0,
	},
];

// Mock Movies Data
export const MOCK_MOVIES: IMovie[] = [
	{
		id: '1',
		title: 'The Dark Knight',
		originalTitle: 'The Dark Knight',
		description:
			'When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
		synopsis:
			'Batman raises the stakes in his war on crime and sets out to dismantle the remaining criminal organizations that plague the city streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
		tagline: 'Why So Serious?',
		posterUrl: '/assets/movies/dark-knight-poster.jpg',
		backdropUrl: '/assets/movies/dark-knight-backdrop.jpg',
		galleryImages: [
			'/assets/movies/dark-knight-1.jpg',
			'/assets/movies/dark-knight-2.jpg',
			'/assets/movies/dark-knight-3.jpg',
			'/assets/movies/dark-knight-4.jpg',
		],
		trailers: mockTrailers,
		genres: [MovieGenre.ACTION, MovieGenre.CRIME, MovieGenre.DRAMA],
		rating: MovieRating.PG_13,
		language: MovieLanguage.ENGLISH,
		subtitleLanguages: [
			MovieLanguage.SPANISH,
			MovieLanguage.FRENCH,
			MovieLanguage.GERMAN,
		],
		duration: 152,
		releaseDate: new Date('2008-07-18'),
		status: MovieStatus.NOW_SHOWING,
		director: ['Christopher Nolan'],
		cast: mockCast,
		crew: mockCrew,
		ratings: mockRatings,
		reviews: mockReviews,
		boxOffice: {
			budget: 185000000,
			domesticGross: 534858444,
			internationalGross: 469700000,
			worldwideGross: 1004558444,
			currency: 'USD',
		},
		awards: [
			{
				id: '1',
				awardName: 'Academy Award',
				category: 'Best Supporting Actor',
				year: 2009,
				isWinner: true,
			},
			{
				id: '2',
				awardName: 'BAFTA Award',
				category: 'Best Supporting Actor',
				year: 2009,
				isWinner: true,
			},
		],
		format2D: true,
		format3D: false,
		formatIMAX: true,
		formatDolbyAtmos: true,
		aspectRatio: '2.39:1',
		schedules: mockSchedules,
		isBookingOpen: true,
		advanceBookingDays: 7,
		createdAt: new Date('2025-01-01T00:00:00'),
		updatedAt: new Date('2025-06-06T12:00:00'),
		createdBy: 'admin-1',
		isActive: true,
		isPremiere: false,
		isExclusive: false,
		seoTitle: 'The Dark Knight - Book Movie Tickets Online',
		seoDescription:
			"Book tickets for The Dark Knight, Christopher Nolan's masterpiece starring Christian Bale and Heath Ledger. Available in IMAX and Dolby Atmos.",
		keywords: [
			'Batman',
			'Joker',
			'Christopher Nolan',
			'Christian Bale',
			'Heath Ledger',
			'Action',
			'Crime',
			'Drama',
			'IMAX',
		],
		promotionalText:
			'Experience the greatest superhero movie ever made in IMAX!',
		ageRestriction: 13,
		warnings: ['Intense sequences of violence and menace'],
		country: 'United States',
		productionCompany: [
			'Warner Bros. Pictures',
			'Legendary Entertainment',
			'Syncopy',
		],
		distributors: ['Warner Bros. Pictures'],
		officialWebsite: 'https://www.thedarkknight.com',
		socialMediaLinks: {
			facebook: 'https://facebook.com/thedarkknight',
			twitter: 'https://twitter.com/thedarkknight',
			instagram: 'https://instagram.com/thedarkknight',
			youtube: 'https://youtube.com/thedarkknight',
		},
	},
	{
		id: '2',
		title: 'Inception',
		originalTitle: 'Inception',
		description:
			'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
		synopsis:
			'Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state when the mind is at its most vulnerable. This rare ability has made Cobb a coveted player in this treacherous new world of corporate espionage.',
		tagline: 'Your mind is the scene of the crime',
		posterUrl: '/assets/movies/inception-poster.jpg',
		backdropUrl: '/assets/movies/inception-backdrop.jpg',
		galleryImages: [
			'/assets/movies/inception-1.jpg',
			'/assets/movies/inception-2.jpg',
			'/assets/movies/inception-3.jpg',
		],
		trailers: [
			{
				id: '1',
				title: 'Inception - Official Trailer',
				url: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
				thumbnailUrl: '/assets/movies/inception-trailer-thumb.jpg',
				duration: 148,
				isOfficial: true,
			},
		],
		genres: [
			MovieGenre.ACTION,
			MovieGenre.SCIENCE_FICTION,
			MovieGenre.THRILLER,
		],
		rating: MovieRating.PG_13,
		language: MovieLanguage.ENGLISH,
		subtitleLanguages: [MovieLanguage.SPANISH, MovieLanguage.FRENCH],
		duration: 148,
		releaseDate: new Date('2010-07-16'),
		status: MovieStatus.NOW_SHOWING,
		director: ['Christopher Nolan'],
		cast: [
			{
				id: '1',
				name: 'Leonardo DiCaprio',
				role: 'Actor',
				character: 'Dom Cobb',
				profileImage: '/assets/avatars/leonardo-dicaprio.jpg',
				isMainCast: true,
			},
			{
				id: '2',
				name: 'Marion Cotillard',
				role: 'Actor',
				character: 'Mal',
				profileImage: '/assets/avatars/marion-cotillard.jpg',
				isMainCast: true,
			},
			{
				id: '3',
				name: 'Tom Hardy',
				role: 'Actor',
				character: 'Eames',
				profileImage: '/assets/avatars/tom-hardy.jpg',
				isMainCast: true,
			},
		],
		crew: [
			{
				id: '1',
				name: 'Christopher Nolan',
				role: 'Director',
				profileImage: '/assets/avatars/christopher-nolan.jpg',
			},
			{
				id: '2',
				name: 'Wally Pfister',
				role: 'Cinematographer',
				profileImage: '/assets/avatars/wally-pfister.jpg',
			},
		],
		ratings: {
			imdb: 8.8,
			rottenTomatoes: 87,
			metacritic: 74,
			audienceScore: 91,
			totalReviews: 2458963,
			averageRating: 4.4,
		},
		reviews: [],
		boxOffice: {
			budget: 160000000,
			domesticGross: 292587330,
			internationalGross: 539649955,
			worldwideGross: 832237285,
			currency: 'USD',
		},
		awards: [
			{
				id: '1',
				awardName: 'Academy Award',
				category: 'Best Cinematography',
				year: 2011,
				isWinner: true,
			},
		],
		format2D: true,
		format3D: false,
		formatIMAX: true,
		formatDolbyAtmos: false,
		aspectRatio: '2.39:1',
		schedules: [],
		isBookingOpen: true,
		advanceBookingDays: 5,
		createdAt: new Date('2025-01-02T00:00:00'),
		updatedAt: new Date('2025-06-05T10:00:00'),
		createdBy: 'admin-1',
		isActive: true,
		isPremiere: false,
		isExclusive: false,
		seoTitle: 'Inception - Book Movie Tickets Online',
		seoDescription:
			"Book tickets for Inception, Christopher Nolan's mind-bending thriller starring Leonardo DiCaprio.",
		keywords: [
			'Inception',
			'Leonardo DiCaprio',
			'Christopher Nolan',
			'Dreams',
			'Science Fiction',
			'Thriller',
		],
		promotionalText: 'Dive into the world of dreams within dreams!',
		ageRestriction: 13,
		warnings: ['Intense sequences of violence and action'],
		country: 'United States',
		productionCompany: ['Warner Bros. Pictures', 'Legendary Entertainment'],
		distributors: ['Warner Bros. Pictures'],
		officialWebsite: 'https://www.inceptionmovie.com',
		socialMediaLinks: {
			facebook: 'https://facebook.com/inception',
			twitter: 'https://twitter.com/inception',
		},
	},
	{
		id: '3',
		title: 'Dune: Part Two',
		originalTitle: 'Dune: Part Two',
		description:
			'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
		synopsis:
			'This follow-up film will explore the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.',
		tagline: 'Long live the fighters',
		posterUrl: '/assets/movies/dune-part-two-poster.jpg',
		backdropUrl: '/assets/movies/dune-part-two-backdrop.jpg',
		galleryImages: [
			'/assets/movies/dune-2-1.jpg',
			'/assets/movies/dune-2-2.jpg',
			'/assets/movies/dune-2-3.jpg',
		],
		trailers: [
			{
				id: '1',
				title: 'Dune: Part Two - Official Trailer',
				url: 'https://www.youtube.com/watch?v=Way9Dexny3w',
				thumbnailUrl: '/assets/movies/dune-2-trailer-thumb.jpg',
				duration: 180,
				isOfficial: true,
			},
		],
		genres: [
			MovieGenre.SCIENCE_FICTION,
			MovieGenre.ADVENTURE,
			MovieGenre.ACTION,
		],
		rating: MovieRating.PG_13,
		language: MovieLanguage.ENGLISH,
		subtitleLanguages: [
			MovieLanguage.SPANISH,
			MovieLanguage.FRENCH,
			MovieLanguage.GERMAN,
		],
		duration: 166,
		releaseDate: new Date('2024-03-01'),
		status: MovieStatus.COMING_SOON,
		director: ['Denis Villeneuve'],
		cast: [
			{
				id: '1',
				name: 'Timothée Chalamet',
				role: 'Actor',
				character: 'Paul Atreides',
				profileImage: '/assets/avatars/timothee-chalamet.jpg',
				isMainCast: true,
			},
			{
				id: '2',
				name: 'Zendaya',
				role: 'Actor',
				character: 'Chani',
				profileImage: '/assets/avatars/zendaya.jpg',
				isMainCast: true,
			},
			{
				id: '3',
				name: 'Rebecca Ferguson',
				role: 'Actor',
				character: 'Lady Jessica',
				profileImage: '/assets/avatars/rebecca-ferguson.jpg',
				isMainCast: true,
			},
		],
		crew: [
			{
				id: '1',
				name: 'Denis Villeneuve',
				role: 'Director',
				profileImage: '/assets/avatars/denis-villeneuve.jpg',
			},
			{
				id: '2',
				name: 'Greig Fraser',
				role: 'Cinematographer',
				profileImage: '/assets/avatars/greig-fraser.jpg',
			},
		],
		ratings: {
			imdb: 8.5,
			rottenTomatoes: 93,
			metacritic: 79,
			audienceScore: 95,
			totalReviews: 456789,
			averageRating: 4.6,
		},
		reviews: [],
		boxOffice: {
			budget: 190000000,
			domesticGross: 282000000,
			internationalGross: 433000000,
			worldwideGross: 715000000,
			currency: 'USD',
		},
		awards: [],
		format2D: true,
		format3D: false,
		formatIMAX: true,
		formatDolbyAtmos: true,
		aspectRatio: '2.39:1',
		schedules: [],
		isBookingOpen: false,
		advanceBookingDays: 14,
		createdAt: new Date('2025-01-03T00:00:00'),
		updatedAt: new Date('2025-06-04T08:00:00'),
		createdBy: 'admin-2',
		isActive: true,
		isPremiere: true,
		isExclusive: false,
		seoTitle: 'Dune: Part Two - Book Movie Tickets Online',
		seoDescription:
			"Book tickets for Dune: Part Two, Denis Villeneuve's epic sci-fi sequel starring Timothée Chalamet and Zendaya.",
		keywords: [
			'Dune',
			'Part Two',
			'Timothée Chalamet',
			'Zendaya',
			'Denis Villeneuve',
			'Science Fiction',
			'IMAX',
		],
		promotionalText: 'The saga continues in spectacular IMAX!',
		ageRestriction: 13,
		warnings: ['Intense sequences of sci-fi violence and action'],
		country: 'United States',
		productionCompany: ['Warner Bros. Pictures', 'Legendary Entertainment'],
		distributors: ['Warner Bros. Pictures'],
		officialWebsite: 'https://www.dunemovie.com',
		socialMediaLinks: {
			facebook: 'https://facebook.com/dunemovie',
			twitter: 'https://twitter.com/dunemovie',
			instagram: 'https://instagram.com/dunemovie',
		},
	},
	{
		id: '4',
		title: 'Spider-Man: No Way Home',
		originalTitle: 'Spider-Man: No Way Home',
		description:
			"With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.",
		synopsis:
			"Peter Parker's secret identity is revealed to the entire world. Desperate for help, Peter turns to Doctor Strange to make the world forget that he is Spider-Man. The spell goes horribly wrong and shatters the multiverse, bringing in foes from other Spider-Man universes.",
		tagline: 'The Multiverse unleashed',
		posterUrl: '/assets/movies/spiderman-nwh-poster.jpg',
		backdropUrl: '/assets/movies/spiderman-nwh-backdrop.jpg',
		galleryImages: [
			'/assets/movies/spiderman-nwh-1.jpg',
			'/assets/movies/spiderman-nwh-2.jpg',
		],
		trailers: [
			{
				id: '1',
				title: 'Spider-Man: No Way Home - Official Trailer',
				url: 'https://www.youtube.com/watch?v=JfVOs4VSpmA',
				thumbnailUrl: '/assets/movies/spiderman-nwh-trailer-thumb.jpg',
				duration: 180,
				isOfficial: true,
			},
		],
		genres: [
			MovieGenre.ACTION,
			MovieGenre.ADVENTURE,
			MovieGenre.SCIENCE_FICTION,
		],
		rating: MovieRating.PG_13,
		language: MovieLanguage.ENGLISH,
		subtitleLanguages: [MovieLanguage.SPANISH, MovieLanguage.FRENCH],
		duration: 148,
		releaseDate: new Date('2021-12-17'),
		status: MovieStatus.ENDED,
		director: ['Jon Watts'],
		cast: [
			{
				id: '1',
				name: 'Tom Holland',
				role: 'Actor',
				character: 'Peter Parker / Spider-Man',
				profileImage: '/assets/avatars/tom-holland.jpg',
				isMainCast: true,
			},
			{
				id: '2',
				name: 'Zendaya',
				role: 'Actor',
				character: 'MJ',
				profileImage: '/assets/avatars/zendaya.jpg',
				isMainCast: true,
			},
			{
				id: '3',
				name: 'Benedict Cumberbatch',
				role: 'Actor',
				character: 'Doctor Strange',
				profileImage: '/assets/avatars/benedict-cumberbatch.jpg',
				isMainCast: true,
			},
		],
		crew: [
			{
				id: '1',
				name: 'Jon Watts',
				role: 'Director',
				profileImage: '/assets/avatars/jon-watts.jpg',
			},
		],
		ratings: {
			imdb: 8.2,
			rottenTomatoes: 90,
			metacritic: 71,
			audienceScore: 98,
			totalReviews: 789456,
			averageRating: 4.5,
		},
		reviews: [],
		boxOffice: {
			budget: 200000000,
			domesticGross: 804793477,
			internationalGross: 1087000000,
			worldwideGross: 1921847111,
			currency: 'USD',
		},
		awards: [],
		format2D: true,
		format3D: true,
		formatIMAX: true,
		formatDolbyAtmos: true,
		aspectRatio: '2.39:1',
		schedules: [],
		isBookingOpen: false,
		advanceBookingDays: 0,
		createdAt: new Date('2025-01-04T00:00:00'),
		updatedAt: new Date('2025-06-03T15:00:00'),
		createdBy: 'admin-1',
		isActive: false,
		isPremiere: false,
		isExclusive: false,
		seoTitle: 'Spider-Man: No Way Home - Movie Information',
		seoDescription:
			'Spider-Man: No Way Home brought together three generations of Spider-Man in an epic multiverse adventure.',
		keywords: [
			'Spider-Man',
			'No Way Home',
			'Tom Holland',
			'Multiverse',
			'Marvel',
			'Action',
			'Adventure',
		],
		promotionalText: '',
		ageRestriction: 13,
		warnings: ['Sequences of action/violence'],
		country: 'United States',
		productionCompany: ['Sony Pictures', 'Marvel Studios'],
		distributors: ['Sony Pictures'],
		officialWebsite: 'https://www.spidermannowayhome.movie',
		socialMediaLinks: {
			twitter: 'https://twitter.com/spidermanmovie',
			instagram: 'https://instagram.com/spidermanmovie',
		},
	},
];

// Mock movie statistics for admin dashboard
export const MOCK_MOVIE_STATISTICS = {
	totalMovies: MOCK_MOVIES.length,
	nowShowing: MOCK_MOVIES.filter((m) => m.status === MovieStatus.NOW_SHOWING)
		.length,
	comingSoon: MOCK_MOVIES.filter((m) => m.status === MovieStatus.COMING_SOON)
		.length,
	totalBookings: 15847,
	averageRating: 4.4,
	genreDistribution: [
		{ genre: MovieGenre.ACTION, count: 4 },
		{ genre: MovieGenre.SCIENCE_FICTION, count: 3 },
		{ genre: MovieGenre.DRAMA, count: 2 },
		{ genre: MovieGenre.THRILLER, count: 2 },
		{ genre: MovieGenre.ADVENTURE, count: 3 },
		{ genre: MovieGenre.CRIME, count: 1 },
	],
	languageDistribution: [
		{ language: MovieLanguage.ENGLISH, count: 4 },
		{ language: MovieLanguage.HINDI, count: 0 },
		{ language: MovieLanguage.SPANISH, count: 0 },
	],
	monthlyReleases: [
		{ month: 'Jan', count: 0 },
		{ month: 'Feb', count: 0 },
		{ month: 'Mar', count: 1 },
		{ month: 'Apr', count: 0 },
		{ month: 'May', count: 0 },
		{ month: 'Jun', count: 2 },
		{ month: 'Jul', count: 1 },
		{ month: 'Aug', count: 0 },
		{ month: 'Sep', count: 0 },
		{ month: 'Oct', count: 0 },
		{ month: 'Nov', count: 0 },
		{ month: 'Dec', count: 1 },
	],
};
